### ISSUE TITLE
Algae results to compile error in multiple places in Elixir 1.9

### ISSUE THREAD

**Issue by liveforeverx** [witchcrafters/algae#56]
It doesn't compile for upcoming Elixir version.

At least this 2 errors prevents algae to compile:
`algae` seems to generate not compatible to Elixir compiler aliases, on Elixir master it results to this error:

```elixir
== Compilation error in file lib/algae/tree/binary_search.ex ==
** (UndefinedFunctionError) function Empty.new/0 is undefined (module Empty is not available)
    Empty.new()
    lib/algae/tree/binary_search.ex:51: (module)
    lib/algae/tree/binary_search.ex:49: (module)
```

Second error is there:

```elixir
== Compilation error in file lib/algae/free/apply.ex ==
** (UndefinedFunctionError) function TypeClass.Property.Generator.Algae.Free.Pure.generate/1 is undefined (module TypeClass.Property.Generator.Algae.Free.Pure is not available)
    TypeClass.Property.Generator.Algae.Free.Pure.generate(nil)
    lib/type_class/property.ex:30: TypeClass.Property.run!/4
    lib/algae/free/apply.ex:6: anonymous fn/2 in :elixir_compiler_72.__FILE__/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/algae/free/apply.ex:6: (file)
```

**Comment by liveforeverx** [comment]
The first error seems to be related to:

```
  * [Kernel] Resolve `__MODULE__` accordingly in nested `defmodule` to avoid double nesting
```

**Comment by liveforeverx** [comment]
FYI: it doesn't compiles on released Elixir `v1.9`.

**Comment by icidasset** [comment]
Thanks! We'll look into this soon.

**Comment by RazgrizHsu** [comment]
elixir 1.9.1 new project compile error..

any update?

```
== Compilation error in file lib/algae/tree/binary_search/monoid.ex ==
** (ArgumentError) Witchcraft.Semigroup.Proto.Algae.Tree.BinarySearch.Empty is not available
    (elixir) lib/protocol.ex:324: Protocol.assert_impl!/3
    lib/algae/tree/binary_search/monoid.ex:8: anonymous fn/2 in :elixir_compiler_55.__FILE__/1
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/algae/tree/binary_search/monoid.ex:8: (file)
could not compile dependency :algae, "mix compile" failed. You can recompile this dependency with "mix deps.compile algae", update it with "mix deps.update algae" or clean it with "mix deps.clean algae"
```

**Comment by icidasset** [comment]
Thanks @RazgrizHsu , I think I've got this fixed.
Will do a release asap.

**Comment by mindreframer** [comment]
Hey @icidasset, are you still planning to get this released? Our team would be happy to use Elixir 1.9 in our project that also depends on Algae... We understand that maintaining open source software is hard work and your life priorities might have changed in the meanwhile... How can we make this happen? Is it on a special branch, do you need some support / reviewers? We would gladly have some from our team members help you to iron the kinks out of it. 

Have a nice weekend!

**Comment by icidasset** [comment]
Oh damn totally forgot, sorry folks.

@mindreframer You can use the `elixir-1.9` branch for now, there's a PR for it here -> #59 
I'll see if I can get my friend to approve my PR and do a release.

**Comment by icidasset** [comment]
Fixed in `1.2.4` https://hex.pm/packages/algae/1.2.4
